origanal = float(input("What is your number?: "))
print()
print("{:,}".format(int(origanal)))
print()
print("{:.4f}".format(origanal))
print()
print("{:.0%}".format(origanal))
print()
print("{:.2f}".format(origanal))
print()